name: test

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run lint
        run: pnpm lint:check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run typecheck
        run: pnpm typecheck

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version:
          - 20.10.0
          - 21.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run tests
        run: pnpm test
